import type { Metadata } from "next";
import { sans_serif, serif, mono } from "./utils/fonts";
import "./globals.css";
import { ModeProvider } from "@/providers/ModeProvider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${serif.variable} ${mono.variable} ${sans_serif.variable}`}
		>
			<body
				suppressHydrationWarning
				className="py-6 sm:py-14  px-6 sm:px-10 dark:bg-black-400 bg-neutral-white"
			>
				<ModeProvider>{children}</ModeProvider>
			</body>
		</html>
	);
}
